# Generated by Django 4.2.7 on 2023-11-21 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mileagedata',
            name='arrival_lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mileagedata',
            name='arrival_lng',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mileagedata',
            name='departure_lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mileagedata',
            name='departure_lng',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mileagedata',
            name='arrival_location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mileagedata',
            name='departure_location',
            field=models.CharField(max_length=255),
        ),
    ]
